### ISSUE TITLE
Move to another store

### ISSUE THREAD

**Issue by johlrogge** [agical/friendsunhosted#26]
At one occation I have changed stores from owncube to 5apps. That was "in the early days". One of the benefits of F#Un is that you are free to take your data with you to another provider for whatever reason you may have.

If you do it would be nice to:
a) get help with moving data from once store to another
b) add a redirect in your old store to your new store so your followers can automatically update to your new location

**Comment by jancborchardt** [comment]
Yeah, we wanted to have that for a long time. :)

This would probably be best not baked into F#un, but rather as a separate storage-switcher app. That way other unhosted apps can also just point to that. And also because you won’t move particularly often.

**Comment by johlrogge** [comment]
If an app like that was available it would be great!
