### ISSUE TITLE
use Bootstrap

### ISSUE THREAD

**Issue by jancborchardt** [agical/friendsunhosted#29]
I guess it’s time to switch to Twitter’s [Bootstrap](http://twitter.github.com/bootstrap) as interface library. With that I don’t mean that everything should look like that, of course it’s only a good groundwork, also in regards to responsive & mobile design.

If you’re cool with that, I’ll start a branch and put it in (also ripping out the ugly jQuery UI where it’s used).

**Comment by johlrogge** [comment]
I haven't tried bootstrap. I'm all for seeing what you can do with it. I know @brolund wants the site to stand out but not necessarily exactly the way it does now. So keeping that in mind I'm curious what you can come up with!

**Comment by jancborchardt** [comment]
See pull #30.
