### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by brolund** [agical/friendsunhosted#33]
So, creative commons seem to be unfit for software. :-P
http://wiki.creativecommons.org/FFAQ#Can_I_apply_a_Creative_Commons_license_to_software.3F

I think GPLv3.
http://opensource.org/licenses/GPL-3.0

Takes on that before I change?

Quote from Neo4Js license manual:

"GNU Public License (GPL)
The GNU Public License Version 3 (GPLv3)
3
 is the common license of the Free Software 
Foundation4
, crafted to protect the following four freedoms:
1. the freedom to use the software for any purpose,
2. the freedom to change the software to suit your needs,
3. the freedom to share the software with your friends and neighbors, and
4. the freedom to share the changes you make.
The spirit of the GPL is to promote open-source software by requiring modiﬁcations or 
elaborations of open-source software to also be open-source. The freedoms concern access to software, considered a public good.
To protect that good, the GPL obligates developers who incorporate open-source software to also release their software as open source. Here, the fair trade for receiving 
software is to contribute software back to the community."

**Comment by brolund** [comment]
"Authors who use or are planning to use the Attribution-ShareAlike 2.0 license should consider a similar Free Software license such as the GNU General Public License [GPL]." http://www.dwheeler.com/essays/gpl-compatible.html

**Comment by jancborchardt** [comment]
Since it’s a web app, it should be [AGPL v3+](https://en.wikipedia.org/wiki/Affero_General_Public_License). This closes a loophole with the GPL where running the software on a server would not make you need to release the source.

**Comment by brolund** [comment]
Ok, we'll go for AGPLv3. Then we can always relax it to GPLv3 if needed. :-)

**Comment by jancborchardt** [comment]
By the way, the AGPL is not a license in terms of »By using the site, you accept the license« (like a EULA), but rather a copyright relaxation document, relevant mainly for developers. I’ll change the footer anyway with donation stuff and the rest of the links. :)
