### ISSUE TITLE
deactivate post and comment buttons when no text to submit

### ISSUE THREAD

**Issue by jancborchardt** [agical/friendsunhosted#36]
Currently, it’s possible to submit an empty comment (empty post does not seem to work). The Post and Comment buttons should be disabled until there is text in the form.

**Comment by brolund** [comment]
I didn't disable the button, but I changed the handling so that nothing happens when double clicking or submitting empty posts.

**Comment by jancborchardt** [comment]
Can you also set it to disabled="disabled"? Then the style changes to grey it out a bit, and it’s more obvious that clicking it does nothing.
