### ISSUE TITLE
Comments "bounce"

### ISSUE THREAD

**Issue by codification** [agical/friendsunhosted#38]
I had a couple of failures to comment just after the new design was launched. Happened both in Safari (5.1.7) and Chrome (21.0.1180.82). I tried pressing the "Comment" button a couple of times and what happened was that each time the contents of the comment box were cleared, stayed clear for a while and were then repopulated (same content, my comment). 

Here are the logs from the Chrome issue ('x':s inserted instead of friends names, just in case):

Uncaught TypeError: undefined is not a function /js/bootstrap.min.js:6
Failed to load resource: the server responded with a status of 404 (Not Found) https://5apps.com/storage/xxxxxxx/public/friendsunhosted_status
Failed to load resource: the server responded with a status of 404 (Not Found) https://5apps.com/storage/xxxxxxx/public/friendsunhosted_status
Error when reading status update for key:friendsunhosted_status Error:404 /js/main.js:432
Failed to load resource: the server responded with a status of 404 (Not Found) https://5apps.com/storage/xxxx/public/friendsunhosted_status
Failed to load resource: the server responded with a status of 404 (Not Found) https://5apps.com/storage/xxxx/public/friendsunhosted_status
Error when reading status update for key:friendsunhosted_status Error:404 /js/main.js:432
Failed to load resource: the server responded with a status of 404 (Not Found) https://5apps.com/storage/xxx/public/friendsunhosted_status
Failed to load resource: the server responded with a status of 404 (Not Found) https://5apps.com/storage/xxx/public/friendsunhosted_status
Error when reading status update for key:friendsunhosted_status Error:404 /js/main.js:432
Failed to load resource: the server responded with a status of 404 (Not Found) https://owncube.com/apps/remoteStorage/WebDAV.php/xxx/remoteStorage/public/friendsunhosted_status
XMLHttpRequest cannot load https://owncube.com/apps/remoteStorage/WebDAV.php/xxx/remoteStorage/public/friendsunhosted_status. Origin http://friendsunhosted.com is not allowed by Access-Control-Allow-Origin.
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://5apps.com/storage/xxxxxxxxxx/public/friendsunhosted_friends
XMLHttpRequest cannot load https://5apps.com/storage/xxxxxxxxxx/public/friendsunhosted_friends. Origin http://friendsunhosted.com is not allowed by Access-Control-Allow-Origin.
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://5apps.com/storage/xxxxx/public/friendsunhosted_status
XMLHttpRequest cannot load https://5apps.com/storage/xxxxx/public/friendsunhosted_status. Origin http://friendsunhosted.com is not allowed by Access-Control-Allow-Origin.
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://5apps.com/storage/xxxxx/public/friendsunhosted_status
XMLHttpRequest cannot load https://5apps.com/storage/xxxxx/public/friendsunhosted_status. Origin http://friendsunhosted.com is not allowed by Access-Control-Allow-Origin.
Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://5apps.com/storage/xxxxx/public/friendsunhosted_status
XMLHttpRequest cannot load https://5apps.com/storage/xxxxx/public/friendsunhosted_status. Origin http://friendsunhosted.com is not allowed by Access-Control-Allow-Origin.
Could set status data: Could not verify written data, possibly because of 0 /js/main.js:436
XMLHttpRequest cannot load https://5apps.com/storage/xxxxx/public/friendsunhosted_status. Origin http://friendsunhosted.com is not allowed by Access-Control-Allow-Origin.
Could set status data: Could not verify written data, possibly because of 0

**Comment by brolund** [comment]
The 404 are expected, those are people that haven't use the site.

The Access-Control-Allow-Origin from seem to come intermittently with a 500, but eventually they work (I have gotten that for my own account several times). Maybe Jan knows more?

**Comment by jancborchardt** [comment]
I have no idea why this happens, I just moved around the HTML and changed CSS. The actions for the buttons shouldn’t be affected.

**Comment by jancborchardt** [comment]
Actually, @codification can you check what exactly causes the error in the first line »Uncaught TypeError: undefined is not a function /js/bootstrap.min.js:6«?
It’s definitely not an issue in the Bootstrap code, so there has to be something wrong with our code somewhere. Can you expand it in the inspector?

**Comment by brolund** [comment]
Well, I moved stuff around a bit as well to make it work. ;-)

As I said in another post, I have filed an issue with 5apps about the "Access-Control-Allow-Origin" problems.

**Comment by codification** [comment]
I have not seen this since the relaunch of the new design.
Closing it.
