### ISSUE TITLE
Email invitation on Friends page 

### ISSUE THREAD

**Issue by brolund** [agical/friendsunhosted#40]
For the cases the friend has no #unhosted account, or it is unknown.

Basically creating a pimped mailto: for the users default mail client to pick up.

Should contain a link that, given logged in, lands the user in the add friend form with the inviting users address prefilled.

**Comment by jancborchardt** [comment]
Yep, there should even be a prefilled message like:
»Hey there, you should join me on Friends#Unhosted. It’s the first decentralized social network where you fully own your data. http://friendsunhosted.com«

**Comment by brolund** [comment]
Ok, first version implemented (is in develop). 

Later we could do a mail-back, so that when you have added the friend that sent you the email, you can mail back with your id (and not by filling the form again, but easier).
