### ISSUE TITLE
Keep whitespace on beginning of line in comments&statuses

### ISSUE THREAD

**Issue by brolund** [agical/friendsunhosted#43]
To be able to add some structure (e.g. for code), replace spaces at beginning of line with &amp;nbsp; and tabs with 4 of those.

**Comment by johlrogge** [comment]
I think that is a path that can only lead to misery once threaded. I think either keep it as it is or enable markdown for comments. For most purposes markdown wont be noticed so you don't have to know you're using it.

A poor mans solution would be to wrap posts in `<pre></pre>`

 even
     github
          doesn't preserve whitespace

```
unless of course
    you put it in a code
        block
```

**Comment by johlrogge** [comment]
didn't mean to close it. It honestly was a mistake eventhough I think it is a terrible idea :)

**Comment by johlrogge** [comment]
I think this markdownparser looks very good: https://github.com/chjj/marked

**Comment by brolund** [comment]
Markdown would be great. I guess github et al has found the security problems already... ;-)

**Comment by jancborchardt** [comment]
Yeah, agree with @johlrogge – whitespace shouldn’t be preserved except in an explicit code block.

**Comment by brolund** [comment]
Instead of just whining about it ;-) I created a new issue #44. :-)

**Comment by johlrogge** [comment]
Yes, I came out much more negative than I intended to. Sorry about that and good response to change the tone to a positive one in #44

**Comment by brolund** [comment]
Well probably do #44. Closing this.
