### ISSUE TITLE
use node http-server

### ISSUE THREAD

**Issue by johlrogge** [agical/friendsunhosted#48]
On most systems SimpleHttpServer for python is installed. Not on arch unless you chose too. That is easy to fix but wouldn't it make more sense to use node http-server?

npm install -g http-server

http-server -p 8000

It can probably be embedded in the tests if needed. I thought since you need node to run the tests anyway we can remove a dependency to python...

**Comment by brolund** [comment]
+1 of course.

**Comment by brolund** [comment]
Pushed to develop. Run npm install in the root to install it. Test runs nicely. Closing this.
