### ISSUE TITLE
Ctrl+Enter to submit

### ISSUE THREAD

**Issue by codification** [agical/friendsunhosted#49]
I think it is annoying to have to use the mouse or Tab+Space or Tab+Enter to submit when I write.
I would much prefer to have something like Ctrl+Enter (in a textarea) submit status updates and comments.

I have made a stab at implementing this by binding a knockout event handler (for keypress) to the statusUpdate text area. Should work the same for comments.

Any opinions on what key combo to use? I kind of like being able to use Enter for writing long paragraphs, that is why I suggest Ctrl+Enter.

**Comment by codification** [comment]
Assigned myself as I have already started looking at it.

**Comment by jancborchardt** [comment]
Good point. This is how Github does it also.

**Comment by brolund** [comment]
I did not follow my own rule and I commented on the FUn site instead of here. 

The hint text in the text field should say something like 

Your comment (Ctrl+Enter to submit)

**Comment by codification** [comment]
My implementation of this has been pushed to the develop branch now.

**Comment by brolund** [comment]
I couldn't get it to work at first, but after some debugging I found that in my browser the enter code was 10 (LF) so I added that. Please check it out. I'll close this. And the next time I'll try to remember to add the issue nr in the git comment. :-)
