### ISSUE TITLE
updating F#U to remoteStorage.js v0.7

### ISSUE THREAD

**Issue by michielbdejong** [agical/friendsunhosted#59]
Hi @brolund,

Good news: @nilclass tagged the release of remoteStorage.js version 0.7.0 yesterday. here is an example of how it works:
https://github.com/michielbdejong/remoteStorage.js/blob/master/example/minimal/index.html
so because sync is "behind" the modules with remoteStorage.js 0.7, the app architecture is a matter of:

```
putting domain code into the module (notes.js in the example)
send controller actions to the module
update the DOM only when the module gives you a change event
```

here are reference docs:
http://remotestoragejs.com/doc/code/files/remoteStorage-js.html

let me know what you think! it would be nice to update this so we can have F#U compatible with the latest lib before we add it on https://unhosted.org/apps/ :)

**Comment by codification** [comment]
How much work would this incur? Any ideas @brolund ?
Can most of it be contained within the remoteAdapter module?

**Comment by brolund** [comment]
Michiel, thanks for the notification! :-)

@codification I hope so. Not sure exactly where the final version of 0.7.0
ended up regarding UI-requirements, earlier versions were a bit opinionated
about the login UI.

/D

2013/1/29 Ville Svärd notifications@github.com

> How much work would this incur? Any ideas @brolundhttps://github.com/brolund?
> Can most of it be contained within the remoteAdapter module?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/agical/friendsunhosted/issues/59#issuecomment-12838275.

## 

---

Daniel Brolund
Agical AB - www.agical.com

work: daniel.brolund@agical.com
phone: +46708754002
blog:http://danielbrolund.wordpress.com
twitter: @danielbrolund
private: daniel.brolund@gmail.com

**Comment by michielbdejong** [comment]
hm, i think we used to have either a setBearerToken function or a setUserAddress function that allowed you to implement your own widget, but i can't find it now on http://remotestoragejs.com/doc/code/files/remoteStorage-js.html

@nilclass is there currently an option to use the library without using the widget?

**Comment by nilclass** [comment]
There are two ways to do it:
1) Use the widget controller and implement your own view (see [here](https://github.com/RemoteStorage/remoteStorage.js/blob/master/src/lib/widget/default.js#L468) for the interface the view needs to expose), then call `remoteStorage.widget.setView(myViewObject)`
2) Use `remoteStorage.nodeConnect`, which exposes `setUserAddress` (discovers storageInfo via webfinger), `setStorageInfo` (to set the storageInfo object directly, without discovery) and `setBearerToken` (you would have to fetch it from the fragment yourself)

**Comment by nilclass** [comment]
The widget view interface is also documented here: http://remotestoragejs.com/doc/code/files/lib/widget/default-js.html

The very least the view needs to do, is fire "connect" at some point, passing in the userAddress.

To implement the events, the view has to expose a `on(eventName, handler)` method. It can also use [remoteStorage.util.getEventEmitter](http://remotestoragejs.com/doc/code/files/lib/util-js.html#util.getEventEmitter) to do that.

**Comment by michielbdejong** [comment]
we now have a new version, full rewrite of the library, based on IndexedDB! also, there is now a contacts module which allows the reuse of your addressbook across multiple apps. do you think we can work together to revive F#U to its full glory? here is some info about migrating to remotestorage.js v0.8: http://community.remotestorage.io/t/migrating-from-0-7-to-0-8/63

**Comment by brolund** [comment]
Hi, I've looked at it, and it is a fairly large rewrite. Lately, I've split my time between a daytime job and finishing a book (http://www.mikadomethod.org/), and I simply can't find the time for it. :-( But I'd happily accept pull requests.

**Comment by michielbdejong** [comment]
Issue more than a year old, closing.
