### ISSUE TITLE
relative dates

### ISSUE THREAD

**Issue by jancborchardt** [agical/friendsunhosted#7]
Currently, the dates on posts are absolute, like:
Wednesday, August 15, 2012 20:24:03
or 13:17:50

Instead, they should be relative, like:
just now
3 hours ago
yesterday
5 days ago
last month

The exact information in the form of »Wednesday, 15 August 2012, 20:24« can be shown on hover.
A great library for relative dates is http://momentjs.com

**Comment by brolund** [comment]
Yes.

**Comment by johlrogge** [comment]
+1

**Comment by brolund** [comment]
Done and deployed!

**Comment by jancborchardt** [comment]
Sweeet!
